### ISSUE TITLE
Missing Path Specified

### ISSUE THREAD

**Issue by BazilaAfridi** [aqeelanwar/PEDRA#92]
Where can I find the models/trained/Indoor/indoor_long/Imagenet/e2e/drone0/drone0 path. There is no such path nor any models folder exist in PEDRA-PEDRA project  folder

**Comment by jamilaandimen** [comment]
Hi, I don't think you need it if you leave `custom_load : False` in the config file like https://github.com/aqeelanwar/PEDRA/blob/master/configs/DeepQLearning.cfg for example

**Comment by BazilaAfridi** [comment]
Ok thanks. Can anyone tell me why this error is occuring?

Traceback (most recent call last):
  File "C:\Users\Microsoft\Downloads\PEDRA-PEDRA\PEDRA-PEDRA\main.py", line 93, in <module>
    env_process, env_folder = start_environment(env_name=cfg.env_name)
  File "C:\Users\Microsoft\Downloads\PEDRA-PEDRA\PEDRA-PEDRA\aux_functions.py", line 73, in start_environment
    env_process = subprocess.Popen(path)
  File "C:\Users\Microsoft\anaconda3\envs\myvenv\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Microsoft\anaconda3\envs\myvenv\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by jamilaandimen** [comment]
Did you download the simulated environment and set up everything like mentioned in read.md file before executing your code?

**Comment by BazilaAfridi** [comment]
Yes I did activated the virtual environment, installed all the packages, downloaded and placed the outdoor_forest environment in the unreal_envs folder, edited the config file(also changed the env_name to outdoor_forest) and when run the python main.py command got this error.

**Comment by BazilaAfridi** [comment]
I have found the solution by using another environment because there is no .exe file for the outdoor_forest environment.

**Comment by jamilaandimen** [comment]
Thant's great :)
